// Fetch pokemon list
export const POKEMON_LIST_REQUESTED = 'POKEMON_LIST_REQUESTED';
export const POKEMON_LIST_SUCCEEDED = 'POKEMON_LIST_SUCCEEDED';
export const POKEMON_LIST_FAILED = 'POKEMON_LIST_FAILED';
export const POKEMON_LIST_CLEARED = 'POKEMON_LIST_CLEARED';

// Fetch pokemon detail
export const POKEMON_DETAIL_REQUESTED = 'POKEMON_DETAIL_REQUESTED';
export const POKEMON_DETAIL_SUCCEEDED = 'POKEMON_DETAIL_SUCCEEDED';
export const POKEMON_DETAIL_FAILED = 'POKEMON_DETAIL_FAILED';
