// Fetch pokemon list
export const POKEMON_LIST_REQUESTED = 'POKEMON_LIST_REQUESTED';
export const POKEMON_LIST_SUCCEEDED = 'POKEMON_LIST_SUCCEEDED';
export const POKEMON_LIST_FAILED = 'POKEMON_LIST_FAILED';
