export const habitatColors = {
  cave: 'gold',
  forest: 'green',
  grassland: 'lime',
  mountain: 'volcano',
  rare: 'purple',
  'rough-terrain': 'orange',
  sea: 'geekblue',
  urban: 'gold',
  'waters-edge': 'cyan',
};

export const typeColors = {
  normal: '',
  fighting: '#d56723',
  flying: '#7DC0D4',
  poison: '#b97fc9',
  ground: '#D1BB41',
  rock: '#a38c21',
  bug: '#729f3f',
  ghost: '#7b62a3',
  steel: '#9eb7b8',
  fire: '#fd7d24',
  water: '#4592c4',
  grass: '#9bcc50',
  electric: '#eed535',
  psychic: '#f366b9',
  ice: '#51c4e7',
  dragon: '#A28993',
  dark: '#707070',
  fairy: '#fdb9e9',
  unknown: '',
  shadow: '',
};
